version: '3.0'

services:
  membershipapi:
    build: .
    environment:
      GIN_MODE: release
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: membership
      DB_USER: postgres
      DB_PW: secretpw
      ALLOW_PAUSE_ON_TRIAL: ""
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
    restart: on-failure

  database:
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_PASSWORD: secretpw
      POSTGRES_USER: postgres
      POSTGRES_DB: membership
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/postgresql/data

  databasetest:
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_PASSWORD: secretpw
      POSTGRES_USER: tester
      POSTGRES_DB: membership
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:6.7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
     - 5053:80

volumes:
  data-volume: